name: Continuous integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6

    - name: Lint check
      run: $(go env GOPATH)/bin/golangci-lint run --config ./golangci.yml ./

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build
      run: make build

    - name: Test
      run: make test
