name: Continuous integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint
      run: DOCKER_BUILDKIT=1 make lint

    - name: Check licenses
      run: DOCKER_BUILDKIT=1 make check-license

    - name: Build
      run: make build

    - name: Test
      run: make test
